# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-22.04

variables:
  phpVersion: 8.2
  chunks: 6

jobs:
  - job: Initialize
    steps:
      - template: system.yml

      - script: drun sh -c '>c250-applist.txt /repo/bin/250 c250-applist "$(CLUB_250_API_TOKEN)"'
        displayName: Download Club 250 app list

      - script: 250 c250-tags
        displayName: Download Club 250 tags list

      - script: retry drun bash -c '>applist.json /repo/bin/250 applist && ls -l applist.json &&
          (($(stat -c%s applist.json) > 4000000))'
        displayName: Download app list

      - script: 250 players-import
        displayName: Import player stats
        condition: and(succeeded(), not(variables['skip-players']))

      - script: data upload "$BUILDDIR" "$RBUILDDIR"
        displayName: Upload build artifacts

  - job: Import
    dependsOn: Initialize
    strategy:
      parallel: $[variables['chunks']]
    steps:
      - template: system.yml

      - script: dig +short myip.opendns.com @resolver1.opendns.com
        displayName: WAN IP

      - script: 250 import --lite --chunks $(System.TotalJobsInPhase) -i $(System.JobPositionInPhase)
          --steam-spy '/repo/data/steamspy 20180411.json' c250-applist.txt
        displayName: Import apps ($(System.JobPositionInPhase)/$(System.TotalJobsInPhase))

      - script: data upload "$BUILDDIR" "$RBUILDDIR"
        displayName: Upload build artifacts

  - job: Stitch
    dependsOn: Import
    steps:
      - template: system.yml

      - script: 250 stitch "$(BUILDDIR)"
        displayName: Stitch

      - script: |
          data upload "$BUILDDIR" "$RBUILDDIR" &&
          data delete "$RBUILDDIR" -p '\.p\d\d?$' &&
          data move "$RBUILDDIR" &&
          data delete $MARKER
        displayName: Upload build artifacts and clean up
        condition: and(succeeded(), not(variables.test))

      - script: |
          [[ '$(Build.Reason)' = Schedule ]] &&
            GITHUB_TOKEN='$(GITHUB_AZURE_TOKEN)' ||
            GITHUB_TOKEN='$(GITHUB_BILGE_TOKEN)'

          curl -sS \
            -u :"$GITHUB_TOKEN" \
            -d '{"ref":"master"}' \
            https://api.github.com/repos/250/Steam-250/actions/workflows/Build.yml/dispatches
        displayName: Trigger Steam 250 repository build
        condition: and(succeeded(), not(variables.test))

      - script: |
          set -v
          data download-last2
          wget --progress=dot:mega\
            https://github.com/meterup/github-release/releases/download/v0.7.4/linux-amd64-github-release.bz2
          bunzip2 -v *.bz2
          chmod -c +x linux-amd64-github-release
          tar cJvf tar *.*
          retry ./linux-amd64-github-release upload --user 250 --repo Steam-250 --tag snapshots \
            --name snapshots.tar.xz --file tar --replace --security-token '$(GITHUB_AZURE_TOKEN)'
        displayName: Upload snapshots
        workingDirectory: $(Build.ArtifactStagingDirectory)
        condition: and(succeeded(), not(variables.test))
