# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-18.04

variables:
  phpVersion: 7.4
  chunks: 6

jobs:
- job: Initialize
  steps:
  - template: system.yml

  - script: retry bash -c '250 applist > applist.json && ls -l applist.json && (($(stat -c%s applist.json) > 4000000))'
    displayName: Download app list
    workingDirectory: $(BUILDDIR)

  - script: PATREON_API_KEY=$(PATREON_API_KEY) 250 patron-import
    displayName: Import patron reviews
    workingDirectory: $(BUILDDIR)
    condition: not(variables['skip-patreon'])

  - script: 250 players-import
    displayName: Import player stats
    workingDirectory: $(BUILDDIR)
    condition: not(variables['skip-players'])

  - script: data upload "$BUILDDIR" "$RBUILDDIR"
    displayName: Upload build artifacts

- job: Import
  dependsOn: Initialize
  strategy:
    parallel: $[variables['chunks']]
  steps:
  - template: system.yml

  - script: dig +short myip.opendns.com @resolver1.opendns.com
    displayName: WAN IP

  - script: 250 import-async --lite --chunks $(System.TotalJobsInPhase) -i $(System.JobPositionInPhase)
      --steam-spy "$(Build.SourcesDirectory)/data/steamspy 20180411.json" applist.json
    displayName: Import apps ($(System.JobPositionInPhase)/$(System.TotalJobsInPhase))
    workingDirectory: $(BUILDDIR)

  - script: retry data upload "$BUILDDIR" "$RBUILDDIR"
    displayName: Upload build artifacts

- job: Stitch
  dependsOn: Import
  steps:
  - template: system.yml

  - script: 250 stitch "$(BUILDDIR)"
    displayName: Stitch

  - script: |
      data upload "$BUILDDIR" "$RBUILDDIR" &&
      data delete "$RBUILDDIR" -p '\.p\d\d?$' &&
      data move "$RBUILDDIR" &&
      data delete $MARKER
    displayName: Upload build artifacts and clean up
    condition: not(variables.test)

  - script: |
      [[ '$(Build.Reason)' = Schedule ]] &&
        TRAVIS_TOKEN='$(TRAVIS_CRON_API_KEY)' ||
        TRAVIS_TOKEN='$(TRAVIS_API_KEY)'

      curl -sSf\
        -H 'Travis-API-Version: 3'\
        -H "Authorization: token $TRAVIS_TOKEN"\
        -H 'Content-Type: application/json'\
        -d '{"request": {"branch": "master"}}'\
        https://api.travis-ci.org/repo/250%2FSteam-250/requests
    displayName: Trigger Steam 250 repository build
    condition: not(variables.test)

  - script: |
      set -v
      retry data download-last2
      wget --progress=dot:mega\
        https://github.com/meterup/github-release/releases/download/v0.7.4/linux-amd64-github-release.bz2
      bunzip2 -v *.bz2
      chmod -c +x linux-amd64-github-release
      tar cJvf tar *.*
      ./linux-amd64-github-release upload --user 250 --repo Steam-250 --tag snapshots --name snapshots.tar.xz \
        --file tar --replace --security-token '$(GITHUB_AZURE_TOKEN)'
    displayName: Upload snapshots
    workingDirectory: $(Build.ArtifactStagingDirectory)
    condition: not(variables.test)
