notifications:
  email: false

sudo: false

language: php

php: 7.1

env:
  # Ensure the main script is always updated to match the number of chunks.
  - chunk=1
  - chunk=2
  - chunk=3
  - chunk=4

cache:
  directories:
    - vendor

install:
  - alias composer=composer\ -n && composer selfupdate
  - composer validate
  - composer install --no-progress --no-suggest

before_script:
  - '[[ $TRAVIS_BRANCH = drive ]]'
#  - echo "https://$GITHUB_TOKEN:@github.com" > ~/.git-credentials
#  - git clone --depth=1 https://github.com/250/Steam-data.git ${datadir=~/Steam-data}
#      -b $TRAVIS_BRANCH
#      -c user.name=Travis
#      -c user.email=bilge+travis@scriptfusion.com
#      -c credential.helper=store
#  - cd "$datadir" && git fetch origin $TRAVIS_BUILD_NUMBER && git checkout -b $TRAVIS_BUILD_NUMBER FETCH_HEAD || true

  - S250() { "$TRAVIS_BUILD_DIR/bin/250" "$@"; }
  - data() { "$TRAVIS_BUILD_DIR/vendor/bin/250 data" "$@"; }

  - mkdir -v ${datadir=~/Steam-data} && cd "$datadir"
  - marker=$TRAVIS_BUILD_NUMBER.date
  - data download -w $marker || true
  - '[[ -e $marker ]] && echo Date marker found. || { echo No date marker.; newmarker=1; }'
  - date=$([[ -e $marker ]] && cat $marker || date -u +%Y%m/%d | tee $marker); echo $date
  - if ((newmarker)); then data upload $marker; fi
  - mkdir -pv "${builddir=$datadir/$date/$TRAVIS_BUILD_NUMBER}"
  - cd "$builddir"
  - data download -w "${rbuilddir=${builddir#$datadir/}}" || true

script:
  - S250 import-async -v --lite --chunks 4 -i $chunk --steam-spy "$TRAVIS_BUILD_DIR/data/steamspy 20180411.json"
      applist.json || exit
  - data upload "$builddir" "$rbuilddir" || exit
#  - git add . &&
#    git checkout -b ${branch=$TRAVIS_BUILD_NUMBER.$chunk} &&
#    git commit -m "Added database chunk $chunk/$chunks for $TRAVIS_COMMIT." &&
#    git push -f origin HEAD:$branch

jobs:
  include:
    - stage: Import app list
      script:
        - S250 applist > applist.json || exit
        - S250 patron-import || exit
        - data upload "$builddir" "$rbuilddir" || exit
#        - git add "$datadir" &&
#          git commit -m "Added applist for $TRAVIS_COMMIT." &&
#          git push origin HEAD:$TRAVIS_BUILD_NUMBER

    - stage: Stitch data chunks
      script:
        S250 stitch . &&
        data upload "$builddir" "$rbuilddir" &&
        data delete "$rbuilddir" -p '\.p\d\d?$' &&
        data move "$rbuilddir" &&
        data delete $marker
        || exit
        # Stitch.
#        - mapfile -t branches <<<"$(git ls-remote origin refs/heads/$TRAVIS_BUILD_NUMBER.* | cut -f2)" &&
#          git pull --no-edit origin "${branches[@]}"
#          || exit
#
#        - S250 stitch . &&
#          git add -A . &&
#          git rm "$datadir/$marker" &&
#          git commit -m "Added stitched database for $TRAVIS_COMMIT." &&
#          git push origin $TRAVIS_BUILD_NUMBER &&
#          git push -d origin "${branches[@]}"
#          || exit
#
        # Merge feature into $TRAVIS_BRANCH.
#        - cd "$datadir" &&
#          git checkout $TRAVIS_BRANCH &&
#          git pull &&
#          git merge $TRAVIS_BUILD_NUMBER &&
#          git push &&
#          git push -d origin $TRAVIS_BUILD_NUMBER
#          || exit

        # Trigger foreign repository build to generate site.
#        - 'curl -sf
#            -H ''Content-Type: application/json''
#            -H ''Travis-API-Version: 3''
#            -H "Authorization: token $TRAVIS_TOKEN"
#            -d ''{"request": {"branch": "master"}}''
#            https://api.travis-ci.org/repo/250%2FSteam-250/requests'

stages:
  - Import app list
