notifications:
  email: false

sudo: false

language: php

php:
  - 7.1

env:
  - chunk=1
  - chunk=2
  - chunk=3
  - chunk=4
  - chunk=5
  - chunk=6
  - chunk=7
  - chunk=8
  - chunk=9
  - chunk=10
  - chunk=11
  - chunk=12
  - chunk=13
  - chunk=14
  - chunk=15

cache:
  directories:
    - vendor

install:
  - alias composer=composer\ -n && composer selfupdate
  - composer validate
  - composer install --no-progress --no-suggest

before_script:
  - echo "https://$GITHUB_TOKEN:@github.com" > ~/.git-credentials
  - git clone --depth=1 https://github.com/250/Steam-data.git ${datadir=~/Steam-data}
      -c user.name=Travis
      -c user.email=bilge+travis@scriptfusion.com
      -c credential.helper=store

  - mkdir -pv "${dbdir=${builddir=$datadir/$TRAVIS_BUILD_NUMBER}/db}"
  - S250() { "$TRAVIS_BUILD_DIR/bin/250" "$@"; }
  - cd "$builddir"

script:
  - S250 reviews -c ${chunks=15} -i $chunk applist.json
  - git add "$dbdir" &&
    git checkout -b ${branch=$TRAVIS_BUILD_NUMBER.$chunk} &&
    git commit -m "Added database chunk $chunk/$chunks for $TRAVIS_COMMIT." &&
    git push -f origin HEAD:$branch

jobs:
  include:
    - stage: Import app list
      script:
        - S250 applist > applist.json
        - git add . &&
          git commit -m "Added applist for $TRAVIS_COMMIT." &&
          git push origin HEAD:master

    - stage: Stitch data chunks and decorate database
      script:
        # Stitch
        - mapfile -t branches <<<"$(git ls-remote origin refs/heads/$TRAVIS_BUILD_NUMBER.* | cut -f2)" &&
          git pull --no-edit origin "${branches[@]}"
          || exit

        - S250 stitch "$dbdir" &&
          git add -A . &&
          git commit -m "Added stitched database for $TRAVIS_COMMIT." &&
          git push &&
          git push -d origin "${branches[@]}"
          || exit

        # Decorate
        - S250 decorate "$dbdir" &&
          git commit -am "Decorated database for $TRAVIS_COMMIT." &&
          git push
          || exit

stages:
  - Import app list
