notifications:
  email: false

sudo: false

language: php

php:
  - 7.1

matrix:
  fast_finish: true

cache:
  directories:
    - .composer/cache

install:
  - alias composer=composer\ -n && composer selfupdate
  - composer validate
  - composer update $DEPENDENCIES

script:
  - bin/import
