notifications:
  email: false

sudo: false

language: php

php:
  - 7.1

env:
  - chunk=1
  - chunk=2
  - chunk=3
  - chunk=4
  - chunk=5
  - chunk=6
  - chunk=7
  - chunk=8
  - chunk=9
  - chunk=10
  - chunk=11
  - chunk=12
  - chunk=13
  - chunk=14
  - chunk=15

cache:
  directories:
    - .composer/cache

install:
  - alias composer=composer\ -n && composer selfupdate
  - composer validate
  - composer install --no-progress --no-suggest

before_script:
  - |
    git clone --depth=1 https://github.com/Bilge/Steam-data.git ${datadir=~/Steam-data} && cd $_
    git config user.name Travis
    git config user.email bilge+travis@scriptfusion.com
    git config credential.helper store
    echo "https://$GITHUB_TOKEN:@github.com" > ~/.git-credentials

  - mkdir -pv "${dbdir=${builddir=$datadir/$TRAVIS_BUILD_NUMBER}/db}"
  - S250() { "$TRAVIS_BUILD_DIR/bin/250" "$@"; }
  - cd "$builddir"

script:
  - S250 reviews -c ${chunks=15} -i $chunk applist.json
  - git add "$dbdir" &&
    git checkout -b ${branch=$TRAVIS_BUILD_NUMBER.$chunk} &&
    git commit -m "Added database chunk $chunk/$chunks for $TRAVIS_COMMIT." &&
    git push -f origin HEAD:$branch

jobs:
  include:
    - stage: Import app list
      script:
        - S250 applist > applist.json
        - git add -A . &&
          git commit -m "Added applist for $TRAVIS_COMMIT." &&
          git push origin HEAD:master

    - stage: Merge data chunks
      script:
        - mapfile -t branches <<<"$(git ls-remote origin refs/heads/$TRAVIS_BUILD_NUMBER.* | cut -f2)" &&
          git pull --no-edit origin "${branches[@]}"
        - S250 stitch "$dbdir"
        - git add -A . &&
          git commit -m "Added stitched database for $TRAVIS_COMMIT." &&
          git push &&
          git push -d origin "${branches[@]}"

stages:
  - Import app list
