notifications:
  email: false

sudo: false

language: php

php: 7.1

branches:
  only:
    - master

env:
  # Ensure the main script is always updated to match the number of chunks.
  - chunk=1
  - chunk=2
  - chunk=3
  - chunk=4

cache:
  directories:
    - vendor

install:
  - alias composer=composer\ -n && composer selfupdate
  - composer validate
  - composer install --no-progress --no-suggest

before_script:
  - S250() { "$TRAVIS_BUILD_DIR/bin/250" -v "$@"; }
  - data() { "$TRAVIS_BUILD_DIR/vendor/bin/250 data" -v "$@"; }

  - mkdir -v ${datadir=~/Steam-data} && cd "$datadir"
  - marker=$TRAVIS_BUILD_NUMBER.date
  - data download -w $marker || true
  - '[[ -e $marker ]] && echo Date marker found. || { echo No date marker.; newmarker=1; }'
  - date=$([[ -e $marker ]] && cat $marker || date -u +%Y%m/%d | tee $marker); echo $date
  - if ((newmarker)); then data upload $marker; fi
  - mkdir -pv "${builddir=$datadir/$date/$TRAVIS_BUILD_NUMBER}"
  - cd "$builddir"
  - data download -w "${rbuilddir=${builddir#$datadir/}}" || true

script:
  - S250 import-async --lite --chunks 4 -i $chunk --steam-spy "$TRAVIS_BUILD_DIR/data/steamspy 20180411.json"
      applist.json || exit
  - data upload "$builddir" "$rbuilddir" || exit

jobs:
  include:
    - stage: Import app list
      script:
        - S250 applist > applist.json || exit
        - S250 patron-import || exit
        - data upload "$builddir" "$rbuilddir" || exit

    - stage: Stitch data chunks
      script:
        - S250 stitch . &&
          data upload "$builddir" "$rbuilddir" &&
          data delete "$rbuilddir" -p '\.p\d\d?$' &&
          data move "$rbuilddir" &&
          data delete $marker
          || exit

        # Trigger foreign repository build to generate site.
        - 'curl -sf
          -H ''Content-Type: application/json''
          -H ''Travis-API-Version: 3''
          -H "Authorization: token $TRAVIS_TOKEN"
          -d ''{"request": {"branch": "master"}}''
          https://api.travis-ci.org/repo/250%2FSteam-250/requests'

stages:
  - Import app list
